name: ScheduleBuild

on:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
