name: Test

on:
  schedule:
    - cron: "0 13 */1 * *"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild
    - name: Run tests
      run: swift test -v
